const About = () => {
    return <div>
      
  <h1>Men haqimda</h1>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel soluta eius maiores reprehenderit, molestias praesentium. Iusto sit labore amet assumenda expedita aliquid placeat iste doloribus, facere officia accusantium eligendi ducimus culpa magni fugiat nesciunt voluptatibus omnis necessitatibus, facilis consequatur mollitia odio eaque quaerat quia. Necessitatibus dolore tempore maiores dolorem inventore sed vitae, deleniti laudantium officiis ab nihil voluptatibus. Corporis nemo eligendi aut voluptas in sed eum iure reprehenderit, possimus laboriosam quos! Dicta repellendus quaerat sapiente minus accusamus, natus similique laboriosam. A eius dolores possimus recusandae tempora inventore esse magnam veniam amet minima commodi dolor totam quo molestiae, nam officia ab. Neque rerum pariatur ipsa cumque, iure illum provident impedit est earum? Dicta a asperiores aspernatur delectus laborum qui quia tenetur necessitatibus blanditiis consequuntur aliquid, alias iusto laudantium maiores, sed minus placeat quis rerum perspiciatis non et. Amet pariatur repudiandae atque quod, inventore reiciendis ex voluptatibus tempore consequuntur possimus, corrupti maxime dolor voluptatem. Eligendi soluta expedita dicta esse culpa possimus iure, quisquam veritatis nostrum quis atque totam sint voluptatem quia vel quasi neque, delectus facilis ullam. Velit consectetur dignissimos laborum minus molestiae itaque optio libero enim sint blanditiis nobis alias, veritatis necessitatibus! Corporis tempora, velit eveniet id accusamus consectetur vitae quidem est repellendus veniam, sint blanditiis officiis eum animi ut nemo cum in excepturi reiciendis facere sapiente voluptatum porro. Vel temporibus animi fuga aliquam, incidunt quo, doloribus quod sit dolores voluptates ipsam non beatae quam eligendi itaque voluptatum sequi qui rem quia praesentium nesciunt perspiciatis porro? Doloremque, assumenda? Quae quidem necessitatibus soluta illo saepe, officia placeat expedita recusandae maiores alias ea, repellat repudiandae distinctio nihil quo eius praesentium iste magnam dolorum deleniti omnis nemo quaerat. Nulla saepe reprehenderit deserunt laudantium aut. Porro harum reiciendis facilis molestiae repudiandae vitae quae placeat? Deleniti quo quasi ab laboriosam magnam inventore, non nesciunt quam voluptas!</p>
    </div>;
  };
  
  export default About;
  